# Generated by Django 5.0.6 on 2024-05-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlm_madlibs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLM_text',
        ),
    ]
